name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Verify repository contents
        run: |
          echo "Listing repository contents:"
          ls -la
          echo "Listing src directory:"
          ls -la src || echo "ERROR: src directory not found"
          echo "Listing public directory:"
          ls -la public || echo "ERROR: public directory not found"
          echo "Listing i18n directory:"
          ls -la i18n || echo "ERROR: i18n directory not found"
          echo "Checking .gitignore:"
          cat .gitignore || echo "ERROR: .gitignore not found"
          echo "Checking package.json:"
          cat package.json || echo "ERROR: package.json not found"
          echo "Checking vite.config.js:"
          cat vite.config.js || echo "ERROR: vite.config.js not found"
          echo "Checking src/App.jsx:"
          cat src/App.jsx || echo "ERROR: src/App.jsx not found"
          echo "Checking src/index.jsx:"
          cat src/index.jsx || echo "ERROR: src/index.jsx not found"
          echo "Checking i18n/es.json:"
          cat i18n/es.json || echo "ERROR: i18n/es.json not found"
          echo "Checking i18n/he.json:"
          cat i18n/he.json || echo "ERROR: i18n/he.json not found"
          echo "Checking i18n/en.json:"
          cat i18n/en.json || echo "ERROR: i18n/en.json not found"
          echo "Checking i18n/pt.json:"
          cat i18n/pt.json || echo "ERROR: i18n/pt.json not found"
          echo "Checking i18n/fr.json:"
          cat i18n/fr.json || echo "ERROR: i18n/fr.json not found"
          echo "Checking i18n/it.json:"
          cat i18n/it.json || echo "ERROR: i18n/it.json not found"
          echo "Checking i18n/ja.json:"
          cat i18n/ja.json || echo "ERROR: i18n/ja.json not found"
          echo "Checking i18n/ko.json:"
          cat i18n/ko.json || echo "ERROR: i18n/ko.json not found"
          echo "Checking public/index.html:"
          cat public/index.html || echo "ERROR: public/index.html not found"

      - name: Clean npm cache
        run: |
          echo "Cleaning npm cache:"
          npm cache clean --force

      - name: Install dependencies
        run: |
          echo "Running npm ci:"
          npm ci || { echo "ERROR: npm ci failed"; cat npm-debug.log || echo "No npm-debug.log found"; exit 1; }

      - name: Verify installed dependencies
        run: |
          echo "Listing installed dependencies:"
          npm list --depth=0 || echo "ERROR: npm list failed"

      - name: Check Node and npm versions
        run: |
          echo "Node version:"
          node --version
          echo "npm version:"
          npm --version

      - name: Check Vite config
        run: |
          echo "Checking vite.config.js content:"
          cat vite.config.js || echo "ERROR: vite.config.js not found"

      - name: Build
        run: |
          echo "Running npm run build:"
          npm run build || { echo "ERROR: npm run build failed"; exit 1; }
        env:
          VITE_BASE_URL: /IA-generativa-Profesor-de-Ritmo/

      - name: Check build output
        run: |
          echo "Checking dist directory:"
          ls -la dist || echo "ERROR: dist directory not found"
          echo "Checking dist/index.html:"
          cat dist/index.html || echo "ERROR: index.html not found in dist"
          echo "Checking dist/assets:"
          ls -la dist/assets || echo "ERROR: dist/assets directory not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          keep_files: false
