name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        continue-on-error: false

      - name: Verify Node and npm versions
        run: |
          node --version
          npm --version

      - name: Verify package.json
        run: cat package.json

      - name: Build
        run: npm run build
        env:
          VITE_BASE_URL: /IA-generativa-Profesor-de-Ritmo/

      - name: Check build output
        run: |
          ls -la dist
          cat dist/index.html || echo "index.html not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          keep_files: false
